export const TopBarTexts = [
	"also try minecraft!",
	"also try terraria!",
	'not even the best game on the site',
	'not a virus, but it might infect your brain',
	'tom says hi',
	'known by the state of california',
	'not a cult, usually',
	"probably a cult",
	"what's good",
	'you are not a fish',
	'you are a fish',
	'you might be a fish',
	'🐇',
	'🐈',
	"🐟",
	"TIP: be good",
];