<script lang="ts">
	import Option from '$lib/components/options/Option.svelte';
	import { Game, game } from '$lib/game/Game.svelte';
	import { onDestroy } from 'svelte';
	import { GenerateDemonym, GetCityClass, toTitleCase } from '$lib/util/Util';

	let cityWordCount = $derived(game.PlayerCity.name.trim().split(' ').length);
	$effect(() => {
		game.Settings.autoDemonymIndex = Math.min(game.Settings.autoDemonymIndex, cityWordCount - 1);
	});

	onDestroy(() => {
		game.PlayerCity.name = game.PlayerCity.name.trim();
		if (game.PlayerCity.name.length === 0) {
			game.PlayerCity.name = Game.Defaults.PlayerCity.name;
		}
	});
</script>

<p class="mb-8 font-serif text-4xl">Options</p>

<Option label="Rename the city:">
	<label for="kingdomName">The {toTitleCase(GetCityClass(game.PlayerCity.people.population))} of</label>
	<input
		type="text"
		id="kingdomName"
		maxlength="24"
		autocomplete="off"
		spellcheck="false"
		class="w-full max-w-96 border-b border-zinc-500/75 bg-transparent p-2 font-serif text-xl outline-none"
		placeholder={Game.Defaults.PlayerCity.name}
		bind:value={game.PlayerCity.name}
		onfocusout={() => (game.PlayerCity.name = game.PlayerCity.name.trim())}
	/>

	<div class="py-2">
		<input bind:checked={game.Settings.autoGenerateDemonym} type="checkbox" id="autoGenerateDemonym" />
		<label for="autoGenerateDemonym">
			Automatically generate demonym {cityWordCount > 1 ? `(${cityWordCount} choices)` : ''}
		</label>
	</div>

	{#if game.Settings.autoGenerateDemonym}
		{#if cityWordCount > 1}
			<label for="wordSelect" class="py-2 pr-2">Your people are:</label>
			<select
				id="wordSelect"
				class="rounded-md border border-zinc-500/75 bg-zinc-800/25 px-2 py-1"
				bind:value={game.Settings.autoDemonymIndex}
			>
				{#each game.PlayerCity.name.trim().split(' ') as word, i}
					<option class="bg-zinc-900" value={i}>{GenerateDemonym(word)}</option>
				{/each}
			</select>
		{/if}
	{:else}
		<div class="py-2">
			<label for="customDemonym">Enter your own demonym:</label>
			<input
				type="text"
				id="customDemonym"
				maxlength="24"
				autocomplete="off"
				spellcheck="false"
				class="w-full max-w-96 border-b border-zinc-500/75 bg-transparent p-2 font-serif text-xl outline-none"
				placeholder={game.PlayerCity.automaticDemonym}
				bind:value={game.Settings.customDemonym}
			/>
		</div>
	{/if}
</Option>

<Option label="Enable scrolling text bar">
	<input bind:checked={game.Settings.enableScrollingText} type="checkbox" id="enableScrollingText" />
	<label for="enableScrollingText">
		Whether to display the scrolling text bar<br />
		{#if !game.Settings.enableScrollingText}
			<span class="text-xs">I don't blame you.</span>
		{/if}
	</label>
</Option>
