<script lang="ts">
	import { Game, game } from '$lib/game/Game.svelte';
	import { onDestroy } from 'svelte';
	import { blur } from 'svelte/transition';
	import { GenerateDemonym } from '$lib/util/Util';
	import OptionsCategory from '$lib/components/options/OptionsCategory.svelte';
	import StyledInput from '$lib/components/options/StyledInput.svelte';
	import AutoDualColumn from '$lib/components/options/AutoDualColumn.svelte';
	import { browser } from '$app/environment';

	let acceptedDebugModeWarning: boolean = $state(game.Settings.debugMode);

	let wantsToDeleteSave: boolean = $state(false);

	let cityWordCount = $derived(game.City.name.trim().split(' ').length);
	$effect(() => {
		game.City.autoDemonymWordIndex = Math.min(game.City.autoDemonymWordIndex, cityWordCount - 1);
	});

	onDestroy(() => {
		game.City.name = game.City.name.trim();
		if (game.City.name.length === 0) {
			game.City.name = Game.Defaults.City.name;
		}

		// why on earth does onDestroy run on the server and NONE of the other lifecycle methods
		if (browser) {
			game.SaveState();
		}
	});
</script>

<div class="max-w-lg">
	<p class="mb-8 font-serif text-4xl">Options</p>

	<OptionsCategory title="City">
		<AutoDualColumn>
			<StyledInput
				id="cityName"
				label="Name"
				type="text"
				placeholder={Game.Defaults.City.name}
				bind:value={game.City.name}
				onfocusout={() => (game.City.name = game.City.name.trim())}
			/>
		</AutoDualColumn>

		<div class="py-2">
			<input bind:checked={game.City.autoGenerateDemonym} type="checkbox" id="autoGenerateDemonym" />
			<label for="autoGenerateDemonym">Automatically generate demonym {cityWordCount > 1 ? `(${cityWordCount} choices)` : ''} </label>
		</div>

		{#if game.City.autoGenerateDemonym && cityWordCount > 1}
			<AutoDualColumn>
				<label for="wordSelect" class="py-2 pr-2">Your people are:</label>
				<select
					id="wordSelect"
					class="rounded-md border border-zinc-500/75 bg-zinc-800/25 px-2 py-1"
					bind:value={game.City.autoDemonymWordIndex}
				>
					{#each game.City.name.trim().split(' ') as word, i}
						<option class="bg-zinc-900" value={i}>{GenerateDemonym(word)}</option>
					{/each}
				</select>
			</AutoDualColumn>
		{/if}

		{#if !game.City.autoGenerateDemonym}
			<AutoDualColumn>
				<StyledInput
					id="customDemonym"
					label="Your people are:"
					type="text"
					placeholder={GenerateDemonym(game.City.name.split(' ')[game.City.autoDemonymWordIndex])}
					bind:value={game.City.customDemonym}
					onfocusout={() => (game.City.customDemonym = game.City.customDemonym.trim())}
				/>
			</AutoDualColumn>
		{/if}
	</OptionsCategory>

	<OptionsCategory title="UI features">
		<input bind:checked={game.Settings.enableScrollingText} type="checkbox" id="enableScrollingText" />
		<label for="enableScrollingText">
			Enable the scrolling text bar<br />
			{#if !game.Settings.enableScrollingText}
				<span class="text-xs">I don't blame you.</span>
			{/if}
		</label>
	</OptionsCategory>

	<OptionsCategory title="Miscellaneous">
		<input
			bind:checked={acceptedDebugModeWarning}
			type="checkbox"
			id="debugModeWarning"
			onchange={(e) => {
				if (!e.currentTarget.checked) {
					game.Settings.debugMode = false;
				}
			}}
		/>
		<label for="debugModeWarning">Enable extras which may be useful for debugging</label>

		{#if acceptedDebugModeWarning}
			<p class="py-2 text-yellow-500">
				This is a bunch of boring behind-the-scenes stuff that will almost certainly ruin the game for you. There are no jokes or secrets
				here.
			</p>
			<input bind:checked={game.Settings.debugMode} type="checkbox" id="enableDebugMode" />
			<label for="enableDebugMode">I understand (enable)</label>
		{/if}

		<div class="rounded-lg border-red-600 p-4" class:border={wantsToDeleteSave} class:mt-2={wantsToDeleteSave}>
			{#if !wantsToDeleteSave}
				<button class="block text-red-600 underline hover:text-red-500" onclick={() => (wantsToDeleteSave = true)}>
					Delete my save (will ask for confirmation)
				</button>
			{:else}
				<p class="pb-2 font-bold">
					This will <span class="underline">permanently delete</span> all of your progress. There are no further warnings.
				</p>

				<button class="mr-16 text-yellow-500 underline hover:text-yellow-400" onclick={() => (wantsToDeleteSave = false)}>Cancel</button>
				<button
					class="text-red-600 underline hover:text-red-500"
					onclick={() => {
						game.Settings.enableSaving = false;
						localStorage.removeItem('state');
						location.reload();
					}}
				>
					Delete my save
				</button>
			{/if}
		</div>
	</OptionsCategory>

	{#if game.Settings.debugMode}
		<div transition:blur>
			<OptionsCategory title="Debug">
				<AutoDualColumn>
					<StyledInput id="debugPeasantPop" label="Peasant pop." type="number" bind:value={game.City.people.peasants} />
					<StyledInput id="debugArtisanPop" label="Artisan pop." type="number" bind:value={game.City.people.artisans} />
					<StyledInput id="debugMerchantPop" label="Merchant pop." type="number" bind:value={game.City.people.merchants} />
					<StyledInput id="debugDaysPerSecond" label="Days per second" type="number" bind:value={game.Time.daysPerSecond} />
				</AutoDualColumn>
			</OptionsCategory>
		</div>
	{/if}
</div>
